# https://taskfile.dev
version: '2'
tasks:
  install:
    desc: install or upgrade Pow by http://pow.cx/
    cmds:
      - curl get.pow.cx | sh
  show-script:
    cmds:
      - curl get.pow.cx 
  missing-app:
    desc: show help when missing deployed app
    cmds:
      - open http://missing.127.0.0.1.xip.io/